from app.db.session import Base
from .user import User
from .historical_data import HistoricalData
from .weather import Weather
from .event import Event
from .prediction import Prediction
from .alert import Alert
from .model_log import ModelLog
from .api_key import ApiKey
