""" Initial schema

Revision ID: 52395a6e9608
Revises: 
Create Date: 2026-08-06 16:24:31.459087

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '52395a6e9608'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('region', sa.String(), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('event_type', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_events_date'), 'events', ['date'], unique=False)
    op.create_index(op.f('ix_events_id'), 'events', ['id'], unique=False)
    op.create_index(op.f('ix_events_region'), 'events', ['region'], unique=False)
    op.create_table('historical_data',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('region', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('load_mw', sa.Float(), nullable=True),
    sa.Column('sector', sa.String(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_historical_data_id'), 'historical_data', ['id'], unique=False)
    op.create_index(op.f('ix_historical_data_region'), 'historical_data', ['region'], unique=False)
    op.create_index(op.f('ix_historical_data_timestamp'), 'historical_data', ['timestamp'], unique=False)
    op.create_table('model_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('model_version', sa.String(), nullable=True),
    sa.Column('trained_at', sa.DateTime(), nullable=True),
    sa.Column('mae', sa.Float(), nullable=True),
    sa.Column('rmse', sa.Float(), nullable=True),
    sa.Column('mape', sa.Float(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_model_logs_id'), 'model_logs', ['id'], unique=False)
    op.create_table('predictions',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('region', sa.String(), nullable=True),
    sa.Column('predicted_for', sa.DateTime(), nullable=True),
    sa.Column('horizon', sa.String(), nullable=True),
    sa.Column('predicted_load', sa.Float(), nullable=True),
    sa.Column('confidence_low', sa.Float(), nullable=True),
    sa.Column('confidence_high', sa.Float(), nullable=True),
    sa.Column('model_version', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_predictions_id'), 'predictions', ['id'], unique=False)
    op.create_index(op.f('ix_predictions_predicted_for'), 'predictions', ['predicted_for'], unique=False)
    op.create_index(op.f('ix_predictions_region'), 'predictions', ['region'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('password_hash', sa.String(), nullable=True),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('weather',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('region', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('temperature', sa.Float(), nullable=True),
    sa.Column('humidity', sa.Float(), nullable=True),
    sa.Column('rainfall', sa.Float(), nullable=True),
    sa.Column('wind_speed', sa.Float(), nullable=True),
    sa.Column('solar_radiation', sa.Float(), nullable=True),
    sa.Column('aqi', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_weather_id'), 'weather', ['id'], unique=False)
    op.create_index(op.f('ix_weather_region'), 'weather', ['region'], unique=False)
    op.create_index(op.f('ix_weather_timestamp'), 'weather', ['timestamp'], unique=False)
    op.create_table('alerts',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('region', sa.String(), nullable=True),
    sa.Column('alert_type', sa.String(), nullable=True),
    sa.Column('triggered_at', sa.DateTime(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('prediction_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['prediction_id'], ['predictions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alerts_id'), 'alerts', ['id'], unique=False)
    op.create_index(op.f('ix_alerts_region'), 'alerts', ['region'], unique=False)
    op.create_table('api_keys',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('key_hash', sa.String(), nullable=True),
    sa.Column('label', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.Column('rate_limit_per_min', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('api_keys')
    op.drop_index(op.f('ix_alerts_region'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_id'), table_name='alerts')
    op.drop_table('alerts')
    op.drop_index(op.f('ix_weather_timestamp'), table_name='weather')
    op.drop_index(op.f('ix_weather_region'), table_name='weather')
    op.drop_index(op.f('ix_weather_id'), table_name='weather')
    op.drop_table('weather')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_predictions_region'), table_name='predictions')
    op.drop_index(op.f('ix_predictions_predicted_for'), table_name='predictions')
    op.drop_index(op.f('ix_predictions_id'), table_name='predictions')
    op.drop_table('predictions')
    op.drop_index(op.f('ix_model_logs_id'), table_name='model_logs')
    op.drop_table('model_logs')
    op.drop_index(op.f('ix_historical_data_timestamp'), table_name='historical_data')
    op.drop_index(op.f('ix_historical_data_region'), table_name='historical_data')
    op.drop_index(op.f('ix_historical_data_id'), table_name='historical_data')
    op.drop_table('historical_data')
    op.drop_index(op.f('ix_events_region'), table_name='events')
    op.drop_index(op.f('ix_events_id'), table_name='events')
    op.drop_index(op.f('ix_events_date'), table_name='events')
    op.drop_table('events')
    # ### end Alembic commands ###
